#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S4,     accel,               sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     motorLeft,     tmotorNormal, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorRight,    tmotorNormal, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#if 0
/// Copyright (c) Michael Tsang. All rights reserved.
///
/// <module name="BalanceDrive.c" />
///
/// <summary>
///     This module contains the main code.
/// </summary>
///
/// <remarks>
///     Environment: RobotC for Lego Mindstorms NXT.
/// </remarks>
#endif

#include "joystickdriver.c"
#include "..\trclib\trcdefs.h"
#include "..\trclib\dbgtrace.h"
#include "..\trclib\batt.h"
#include "..\trclib\nxtbtn.h"
#include "..\trclib\pidctrl.h"
#include "..\trclib\drive.h"
DRIVE   g_Drive[1];
PIDCTRL g_PIDCtrl[2];
#include "..\trclib\piddrive.h"
#include "..\trclib\accel.h"
#include "..\GetOverIt\RobotInfo.h"

#ifdef MOD_ID
    #undef MOD_ID
#endif
#define MOD_ID                  MOD_MAIN

//
// Trace info.
//
#define TRACE_MODULES           (MOD_MAIN)
#define TRACE_LEVEL             TASK
#define MSG_LEVEL               INFO

//
// Global data.
//
bool     g_fBalanceEnabled = false;
BATT     g_Batt;
NXTBTN   g_NxtBtn;
ACCEL    g_Accel;
PIDDRIVE g_BalanceDrive;

/**
 *  This function handles the NXT button events.
 *
 *  @param nxtbtn Points to the NXTBTN structure.
 *  @param nxtButton Specifies the button that generated the event.
 *  @param fPressed If true, the button was pressed, otherwise it was
 *         released.
 */
void
NxtBtnEvent(
    __in NXTBTN &nxtbtn,
    __in int nxtButton,
    __in bool fPressed
    )
{
    TFuncName("NxtBtnEvent");
    TLevel(EVENT);
    TEnterMsg(("Button=%d,On=%d", nxtButton, (byte)fPressed));

    switch (nxtButton)
    {
        case kEnterButton:
            if (fPressed)
            {
                g_fBalanceEnabled = !g_fBalanceEnabled;
                if (g_fBalanceEnabled)
                {
                    PIDDriveSetTarget(g_BalanceDrive,
                                      0.0, BALANCE_DRIVE_TOLERANCE,
                                      0.0, BALANCE_TURN_TOLERANCE,
                                      false);
                }
                else
                {
                    PIDDriveReset(g_BalanceDrive);
                }
            }
            break;

        case kExitButton:
            break;

        case kLeftButton:
            break;

        case kRightButton:
            break;
    }

    TExit();
    return;
}   //NxtBtnEvent

/**
 *  This function provides the input value for various PID controllers.
 *
 *  @param pidCtrlID Specifies the PID Controller ID.
 *
 *  @return Returns the input value for the PID controller.
 */
float
PIDCtrlGetInput(
    __in int pidCtrlID
    )
{
    float inputValue = 0.0;

    TFuncName("PIDCtrlGetInput");
    TLevel(CALLBK);
    TEnterMsg(("ID=%d", pidCtrlID));

    switch (pidCtrlID)
    {
        case 0:
            //
            // Balance Drive.
            //
            AccelGetX(g_Accel, inputValue);
            nxtDisplayTextLine(0, "Drive=%f", inputValue);
            break;

        case 1:
            //
            // Balance Turn.
            //
            AccelGetY(g_Accel, inputValue);
            nxtDisplayTextLine(1, "Turn =%f", inputValue);
            break;
    }

    TExitMsg(("=%5.1f", inputValue));
    return inputValue;
}   //PIDCtrlGetInput

/**
 *  This function handles the drive notification events.
 *
 *  @param drive Points to the DRIVE structure that generated the event.
 */
void
PIDDriveEvent(
    __in PIDDRIVE &pidDrive
    )
{
    TFuncName("PIDDriveEvent");
    TLevel(EVENT);
    TEnter();

    TExit();
    return;
}   //PIDDriveEvent

/**
 *  This function initializes the robot and its subsystems.
 */
void
RobotInit()
{
    TFuncName("RobotInit");
    TLevel(INIT);
    TEnter();

    BattInit(g_Batt, 7, false);
    NxtBtnInit(g_NxtBtn, NXTBTNF_ENABLE_EVENTS);
    //
    // Initialize the accelerometer.
    //
    AccelInit(g_Accel, accel, 0);
    //
    // Initialize the PID Drive subsystem.
    //
    DriveInit(g_Drive[0],
              motorLeft,
              motorRight,
              DISTANCE_PER_CLICK,
              DEGREES_PER_CLICK);
    PIDCtrlInit(g_PIDCtrl[0], 0,
                BALANCE_DRIVE_KP, BALANCE_DRIVE_KI, BALANCE_DRIVE_KD,
                -50, 50,
                PIDCTRLF_INVERSE | PIDCTRLF_ABS_SETPOINT);
    PIDCtrlInit(g_PIDCtrl[1], 1,
                BALANCE_TURN_KP, BALANCE_TURN_KI, BALANCE_TURN_KD,
                -50, 50,
                PIDCTRLF_ABS_SETPOINT);
    PIDDriveInit(g_BalanceDrive,
                 0, //g_Drive,
                 0, //BalanceDrive_PIDCtrl,
                 1, //BalanceTurn_PIDCtrl,
                 0);

    TExit();
    return;
}   //RobotInit

/**
 *  This function processes all the high frequency tasks that needs to run
 *  more often than other tasks such as sensor integration tasks.
 */
void
HiFreqTasks()
{
    TFuncName("HiFreqTasks");
    TLevel(TASK);
    TEnter();


    TExit();
    return;
}   //HiFreqTasks

/**
 *  This function processes all the input tasks.
 */
void
InputTasks()
{
    TFuncName("InputTasks");
    TLevel(TASK);
    TEnter();

    NxtBtnTask(g_NxtBtn);

    TExit();
    return;
}   //InputTasks

/**
 *  This function processes all the main tasks.
 */
void
MainTasks()
{
    TFuncName("MainTasks");
    TLevel(TASK);
    TEnter();



    TExit();
    return;
}   //MainTasks

/**
 *  This function processes all the output tasks. Output tasks are where all
 *  the actions are taking place. All other tasks are just changing states of
 *  various objects. There is no action taken until the output tasks.
 */
void
OutputTasks()
{
    TFuncName("OutputTasks");
    TLevel(TASK);
    TEnter();

    PIDDriveTask(g_BalanceDrive);
    DriveTask(g_Drive[0]);
    BattTask(g_Batt);
    nxtDisplayTextLine(2, "L=%d,R=%d",
                       g_Drive[0].leftPower, g_Drive[0].rightPower);

    TExit();
    return;
}   //OutputTasks

/**
 *  This task is the program entry point.
 */
task main()
{
    long nextTime;
    long currTime;

    TraceInit(TRACE_MODULES, TRACE_LEVEL, MSG_LEVEL);

    RobotInit();

    nextTime = nPgmTime;
    while (true)
    {
        TPeriodStart();
        currTime = nPgmTime;
        HiFreqTasks();
        if (currTime >= nextTime)
        {
            nextTime = currTime + LOOP_TIME;

            InputTasks();
            MainTasks();
            OutputTasks();
        }
        TPeriodEnd();

        wait1Msec(1);
    }
}   //main
