#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  none)
#pragma config(Motor,  motorB,          motorDispense, tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorF,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorG,        tmotorNormal, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servoWrist,           tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    servoArmLeft,         tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    servoArmRight,        tServoStandard)
#pragma config(Servo,  srvo_S1_C2_4,    servoScooper,         tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#if 0
/// Copyright (c) Michael Tsang. All rights reserved.
///
/// <module name="ServoTest.c" />
///
/// <summary>
///     This module contains the main code.
/// </summary>
///
/// <remarks>
///     Environment: RobotC for Lego Mindstorms NXT.
/// </remarks>
#endif

#include "joystickdriver.c"
#include "..\trclib\trcdefs.h"
#include "..\trclib\dbgtrace.h"
#include "..\trclib\batt.h"
#include "..\trclib\nxtbtn.h"
#include "..\trclib\servo.h"
#include "..\GetOverIt\RobotInfo.h"

#ifdef MOD_ID
    #undef MOD_ID
#endif
#define MOD_ID                  MOD_MAIN

//
// Trace info.
//
#define TRACE_MODULES           (MOD_MAIN)
#define TRACE_LEVEL             TASK
#define MSG_LEVEL               INFO

//
// Global Data.
//
float  g_WristPos = WRIST_HORIZONTAL;
float  g_ArmPos = ARM_RAISED;
float  g_ScooperPos = SCOOPER_RAISED;
//int    g_DispensePower = 0;
BATT   g_Batt;
NXTBTN g_NxtBtn;
SERVO  g_Wrist;
SERVO  g_ArmLeft;
SERVO  g_ArmRight;
SERVO  g_Scooper;

/**
 *  This function handles the NXT button events.
 *
 *  @param nxtbtn Points to the NXTBTN structure.
 *  @param nxtButton Specifies the button that generated the event.
 *  @param fPressed If true, the button was pressed, otherwise it was
 *         released.
 */
void
NxtBtnEvent(
    __in NXTBTN &nxtbtn,
    __in int nxtButton,
    __in bool fPressed
    )
{
    TFuncName("NxtBtnEvent");
    TLevel(EVENT);
    TEnterMsg(("Button=%d,On=%d", nxtButton, (byte)fPressed));

    switch (nxtButton)
    {
        case kEnterButton:
            if (fPressed)
            {
                g_ScooperPos = (g_ScooperPos == SCOOPER_LOWERED)?
                                SCOOPER_MID:
                               (g_ScooperPos == SCOOPER_MID)?
                                SCOOPER_RAISED: SCOOPER_LOWERED;
                ServoSetAngle(g_Scooper, g_ScooperPos);
                nxtDisplayTextLine(1, "Scooper=%5.1f", g_ScooperPos);
            }
            break;

        case kExitButton:
            break;

        case kLeftButton:
            if (fPressed)
            {
                g_ArmPos = (g_ArmPos == ARM_LOWERED)?
                                ARM_LOW_DISPENSE:
                           (g_ArmPos == ARM_LOW_DISPENSE)?
                                ARM_MID_DISPENSE:
                           (g_ArmPos == ARM_MID_DISPENSE)?
                                ARM_HI_DISPENSE:
                           (g_ArmPos == ARM_HI_DISPENSE)?
                                ARM_RAISED: ARM_LOWERED;
                SetArmAngle(g_ArmPos);
                nxtDisplayTextLine(0, "Arm=%5.1f", g_ArmPos);
            }
            break;

        case kRightButton:
            if (fPressed)
            {
#if 0
                g_DispensePower = (g_DispensePower == 0)?
                                    DISPENSE_PUSH:
                                  (g_DispensePower == DISPENSE_PUSH)?
                                    DISPENSE_PULL: 0;
                motor[motorDispense] = g_DispensePower;
#endif
                g_WristPos = (g_WristPos == WRIST_HORIZONTAL)?
                              WRIST_VERTICAL: WRIST_HORIZONTAL;
                ServoSetAngle(g_Wrist, g_WristPos);
                nxtDisplayTextLine(2, "Wrist=%5.1f", g_WristPos);
            }
            break;
    }

    TExit();
    return;
}   //NxtBtnEvent

/**
 *  This function handles the servo notification events.
 *
 *  @param serv Points to the SERVO structure that generated the event.
 */
void
ServoEvent(
    __in SERVO &serv
    )
{
    TFuncName("ServoEvent");
    TLevel(EVENT);
    TEnterMsg(("motor=%d", serv.servoMotor));

    nxtDisplayTextLine(3, "ServoDone[%d]", serv.servoMotor);

    TExit();
    return;
}   //ServoEvent

/**
 *  This function initializes the robot and its subsystems.
 */
void
RobotInit()
{
    TFuncName("RobotInit");
    TLevel(INIT);
    TEnter();

    BattInit(g_Batt, 7, false);
    NxtBtnInit(g_NxtBtn, NXTBTNF_ENABLE_EVENTS);
    ServoInit(g_ArmLeft,
              servoArmLeft,
              SERVO_POS_PER_DEGREE,
              LeftArmAngle(g_ArmPos),
              SERVOF_ENABLE_EVENTS);
    ServoInit(g_ArmRight,
              servoArmRight,
              SERVO_POS_PER_DEGREE,
              RightArmAngle(g_ArmPos),
              SERVOF_ENABLE_EVENTS);
    wait1Msec(500);
    ServoInit(g_Wrist,
              servoWrist,
              SERVO_POS_PER_DEGREE,
              g_WristPos,
              SERVOF_ENABLE_EVENTS);
    ServoInit(g_Scooper,
              servoScooper,
              SERVO_POS_PER_DEGREE,
              g_ScooperPos,
              SERVOF_ENABLE_EVENTS);

    TExit();
    return;
}   //RobotInit

/**
 *  This function processes all the high frequency tasks that needs to run
 *  more often than other tasks such as sensor integration tasks.
 */
void
HiFreqTasks()
{
    TFuncName("HiFreqTasks");
    TLevel(TASK);
    TEnter();


    TExit();
    return;
}   //HiFreqTasks

/**
 *  This function processes all the input tasks.
 */
void
InputTasks()
{
    TFuncName("InputTasks");
    TLevel(TASK);
    TEnter();

    NxtBtnTask(g_NxtBtn);

    TExit();
    return;
}   //InputTasks

/**
 *  This function processes all the main tasks.
 */
void
MainTasks()
{
    TFuncName("MainTasks");
    TLevel(TASK);
    TEnter();


    TExit();
    return;
}   //MainTasks

/**
 *  This function processes all the output tasks. Output tasks are where all
 *  the actions are taking place. All other tasks are just changing states of
 *  various objects. There is no action taken until the output tasks.
 */
void
OutputTasks()
{
    TFuncName("OutputTasks");
    TLevel(TASK);
    TEnter();

    ServoTask(g_ArmLeft);
    ServoTask(g_ArmRight);
    ServoTask(g_Wrist);
    ServoTask(g_Scooper);
    BattTask(g_Batt);

    TExit();
    return;
}   //OutputTasks

/**
 *  This task is the program entry point.
 */
task main()
{
    long nextTime;
    long currTime;

    TraceInit(TRACE_MODULES, TRACE_LEVEL, MSG_LEVEL);

    RobotInit();

    nextTime = nPgmTime;
    while (true)
    {
        currTime = nPgmTime;
        HiFreqTasks();
        if (currTime >= nextTime)
        {
            nextTime = currTime + LOOP_TIME;

            InputTasks();
            MainTasks();
            OutputTasks();
        }

        wait1Msec(1);
    }
}   //main
