#pragma config(Sensor, S1,     accel,               sensorI2CCustom)
#pragma config(Sensor, S4,     gyro,               sensorI2CCustom)
#pragma config(Motor,  motorA,          motorRight,    tmotorNormal, openLoop, encoder)
#pragma config(Motor,  motorC,          motorLeft,     tmotorNormal, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#if 0
/// Copyright (c) Titan Robotics Club. All rights reserved.
///
/// <module name="Auto.c" />
///
/// <summary>
///     This module contains the entry point for autonomous mode.
///     This is template file and should not be modified. The main competition
///     code should live in AutoMain.h.
/// </summary>
///
/// <remarks>
///     Environment: RobotC for Lego Mindstorms NXT.
/// </remarks>
#endif

#include "JoystickDriver.c"
#include "..\trclib\trcdefs.h"
#include "..\trclib\dbgtrace.h"
#include "..\trclib\menu.h"
#include "GobbInfo.h"
#include "GobbMain.h"

/**
 *  This task is the program entry point.
 */
task main()
{
    long nextTime;
    long currTime;

    TraceInit(TRACE_MODULES, TRACE_LEVEL, MSG_LEVEL);

    //
    // The RobotInit function is provided by student code in main.h.
    //
    RobotInit();

    nextTime = nPgmTime;
    while (true)
    {
        currTime = nPgmTime;
        HiFreqTasks();
        if (currTime >= nextTime)
        {
            nextTime = currTime + LOOP_TIME;

            //
            // The following functions are provided by student code in main.h.
            //
            InputTasks();
            MainTasks();
            OutputTasks();
        }

        wait1Msec(1);
    }
}   //main
